package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.client.DeepSeekClient;
import com.yizhaoqi.smartpai.entity.SearchResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;
import java.util.LinkedHashMap;
import com.yizhaoqi.smartpai.config.AiProperties;
import com.fasterxml.jackson.databind.JsonNode;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private final StringRedisTemplate redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final ConversationService conversationService;
    private final ObjectMapper objectMapper;
    private final AiProperties aiProperties;
    private final ConversationCompressionService compressionService;

    // 停止标志
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();

    /**
     * 搜索知识库工具定义（OpenAI Function Calling 格式）
     */
    private static final List<Map<String, Object>> SEARCH_TOOL = List.of(
        Map.of(
            "type", "function",
            "function", Map.of(
                "name", "search_knowledge_base",
                "description", "搜索知识库文档。当用户问题涉及已上传的文档、文件、知识库内容时调用此工具获取相关信息。对于通用知识、闲聊、数学计算等不需要搜索。",
                "parameters", Map.of(
                    "type", "object",
                    "properties", Map.of(
                        "query", Map.of(
                            "type", "string",
                            "description", "搜索查询语句，用于在知识库中检索相关文档内容"
                        )
                    ),
                    "required", List.of("query")
                )
            )
        )
    );

    public ChatHandler(StringRedisTemplate redisTemplate,
                      HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      ConversationService conversationService,
                      ObjectMapper objectMapper,
                      AiProperties aiProperties,
                      ConversationCompressionService compressionService) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.conversationService = conversationService;
        this.objectMapper = objectMapper;
        this.aiProperties = aiProperties;
        this.compressionService = compressionService;
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息（Agentic RAG），用户ID: {}, 会话ID: {}", userId, session.getId());
        try {
            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);

            // 2. 获取对话历史
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", history.size());

            // 3. 构建 messages（不含 context，让 LLM 决定是否搜索）
            List<Map<String, Object>> messages = buildMessagesForAgenticRAG(history, userMessage);

            // 4. 累积器
            StringBuilder responseBuilder = new StringBuilder();
            StringBuilder toolCallArgs = new StringBuilder();
            AtomicReference<String> toolCallId = new AtomicReference<>(null);
            AtomicBoolean toolCallDetected = new AtomicBoolean(false);

            // 5. 第一次 LLM 调用（流式，带 tools）
            logger.info("发起第一次 LLM 调用（带搜索工具）");
            deepSeekClient.streamWithTools(
                messages,
                SEARCH_TOOL,
                // delta.content → 直接转发前端
                chunk -> {
                    responseBuilder.append(chunk);
                    sendResponseChunk(session, chunk);
                },
                // tool_call.id → 记录
                id -> {
                    toolCallId.set(id);
                    logger.info("LLM 决定调用搜索工具, toolCallId: {}", id);
                },
                // delta.tool_calls.args → 累积
                args -> {
                    toolCallDetected.set(true);
                    toolCallArgs.append(args);
                },
                // onError
                error -> {
                    logger.error("LLM 流式响应错误: {}", error.getMessage(), error);
                    handleError(session, error);
                    sendCompletionNotification(session);
                },
                // onComplete → 判断是否需要第二次调用
                () -> {
                    if (toolCallDetected.get()) {
                        logger.info("LLM 调用了搜索工具，执行搜索并生成第二次调用");
                        executeToolAndRespond(
                            userId, messages, toolCallId.get(), toolCallArgs.toString(),
                            session, conversationId, userMessage, responseBuilder
                        );
                    } else {
                        // LLM 直接回答了（未调用搜索）
                        logger.info("LLM 直接回答，未调用搜索工具");
                        sendCompletionNotification(session);
                        updateConversationHistory(conversationId, userId, userMessage, responseBuilder.toString());
                    }
                }
            );

        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
        }
    }

    /**
     * 构建 Agentic RAG 的消息列表（不含搜索 context，让 LLM 通过工具获取）
     */
    private List<Map<String, Object>> buildMessagesForAgenticRAG(
            List<Map<String, String>> history, String userMessage) {
        List<Map<String, Object>> messages = new ArrayList<>();

        // 1. System 消息（只含规则，不含 <<REF>> 参考信息）
        AiProperties.Prompt promptCfg = aiProperties.getPrompt();
        String systemContent = promptCfg.getRules() != null ? promptCfg.getRules() : "";
        messages.add(Map.of("role", "system", "content", systemContent));

        // 2. 历史消息（类型转换 String → Object）
        if (history != null && !history.isEmpty()) {
            List<Map<String, Object>> typedHistory = new ArrayList<>();
            for (Map<String, String> msg : history) {
                Map<String, Object> typedMsg = new LinkedHashMap<>();
                typedMsg.put("role", msg.get("role"));
                typedMsg.put("content", msg.get("content"));
                typedHistory.add(typedMsg);
            }
            messages.addAll(typedHistory);
        }

        // 3. 当前用户问题
        messages.add(Map.of("role", "user", "content", userMessage));

        return messages;
    }

    /**
     * 执行工具调用（搜索），然后发起第二次 LLM 调用生成最终回答。
     */
    private void executeToolAndRespond(
            String userId,
            List<Map<String, Object>> originalMessages,
            String toolCallId,
            String toolCallArgsJson,
            WebSocketSession session,
            String conversationId,
            String userMessage,
            StringBuilder responseBuilder) {

        try {
            // 1. 解析 LLM 构造的搜索 query
            String searchQuery = parseSearchQuery(toolCallArgsJson);
            if (searchQuery == null || searchQuery.isEmpty()) {
                searchQuery = userMessage; // 回退到原始用户消息
            }
            logger.info("搜索 query: {}", searchQuery);

            // 2. 执行混合搜索（复用现有 searchService）
            List<SearchResult> searchResults = searchService.searchWithPermission(searchQuery, userId, 10);
            logger.info("搜索完成，结果数: {}", searchResults.size());

            // 3. 构建搜索结果文本
            String searchContext = buildContext(searchResults);
            if (searchContext.isEmpty()) {
                searchContext = "（未找到相关文档）";
            }

            // 4. 构建第二次调用的 messages（追加 tool_call 和 tool result）
            List<Map<String, Object>> messagesWithTool = new ArrayList<>(originalMessages);

            // assistant 消息：记录 LLM 调用了哪个工具
            Map<String, Object> assistantToolCall = new LinkedHashMap<>();
            assistantToolCall.put("role", "assistant");
            assistantToolCall.put("tool_calls", List.of(Map.of(
                "id", toolCallId,
                "type", "function",
                "function", Map.of(
                    "name", "search_knowledge_base",
                    "arguments", toolCallArgsJson
                )
            )));
            messagesWithTool.add(assistantToolCall);

            // tool 消息：返回搜索结果
            Map<String, Object> toolResult = new LinkedHashMap<>();
            toolResult.put("role", "tool");
            toolResult.put("tool_call_id", toolCallId);
            toolResult.put("content", searchContext);
            messagesWithTool.add(toolResult);

            // 5. 第二次流式调用（不带 tools，LLM 基于搜索结果直接回答）
            logger.info("发起第二次 LLM 调用（带搜索结果）");
            deepSeekClient.streamResponse(
                messagesWithTool,
                // onChunk
                chunk -> {
                    responseBuilder.append(chunk);
                    sendResponseChunk(session, chunk);
                },
                // onError
                error -> {
                    logger.error("第二次 LLM 调用错误: {}", error.getMessage(), error);
                    handleError(session, error);
                    sendCompletionNotification(session);
                },
                // onComplete
                () -> {
                    String completeResponse = responseBuilder.toString();
                    logger.info("Agentic RAG 响应完成，长度: {}", completeResponse.length());
                    sendCompletionNotification(session);
                    updateConversationHistory(conversationId, userId, userMessage, completeResponse);
                }
            );

        } catch (Exception e) {
            logger.error("工具执行错误: {}", e.getMessage(), e);
            handleError(session, e);
            sendCompletionNotification(session);
        }
    }

    /**
     * 从 tool_call arguments JSON 中提取 query 字段。
     * 如果解析失败，返回 null（调用方会回退到原始用户消息）。
     */
    private String parseSearchQuery(String argumentsJson) {
        try {
            JsonNode argsNode = objectMapper.readTree(argumentsJson);
            String query = argsNode.path("query").asText("");
            if (!query.isEmpty()) {
                return query;
            }
        } catch (Exception e) {
            logger.warn("解析 tool_call arguments 失败: {}", e.getMessage());
        }
        return null;
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);
        
        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }
        
        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }
            
            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userId, String userMessage, String response) {
        String key = "conversation:" + conversationId;
        List<Map<String, String>> history = getConversationHistory(conversationId);
        
        // 获取当前时间戳
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        
        // 添加用户消息（带时间戳）
        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);
        
        // 添加助手回复（带时间戳）
        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        history.add(assistantMsgMap);

        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());

            // 同步到 MySQL（压缩前先持久化，防止数据丢失）
            conversationService.syncToMySQL(conversationId, userId);

            // 检查阈值并触发异步压缩
            compressionService.checkAndCompress(conversationId, history, userId);
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private String buildContext(List<SearchResult> searchResults) {
        if (searchResults == null || searchResults.isEmpty()) {
            return "";
        }

        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = result.getTextContent();
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            context.append(String.format("[%d] (%s) %s\n", i + 1, fileLabel, snippet));
        }
        return context.toString();
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 检查是否需要停止发送
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            // 将chunk包装成JSON格式，匹配前端期望的数据结构
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            session.sendMessage(new TextMessage(errorJson));
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应 
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);
        
        // 设置停止标志
        stopFlags.put(sessionId, true);
        
        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop", 
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }
        
        // 清理停止标志（延迟清理，避免影响当前响应）
        new Thread(() -> {
            try {
                Thread.sleep(2000); // 等待2秒
                stopFlags.remove(sessionId);
                logger.debug("已清理停止标志，会话ID: {}", sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }
}
